# Testing file for ongoing development.
!ArenaConfig
arenas:
  0: !Arena
    passMark: 0
    timeLimit: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      rotations: [90]
  1: !Arena
    passMark: 0
    timeLimit: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 25, y: 0, z: 25}
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: BadGoalMulti
      positions:
      - !Vector3 {x: 15, y: 0, z: 15}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 10, y: 0, z: 10}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: HotZone
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} 
    - !Item
      name: RipenGoal
      positions:
      - !Vector3 {x: 5, y: 0, z: 5}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
  2: !Arena
    passMark: 0
    timeLimit: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: CylinderTunnel
      positions:
      - !Vector3 {x: 37, y: 2, z: 37}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      colors:
      - !RGB {r: 255, g: 0, b: 255}

    - !Item
      name: CylinderTunnelTransparent
      positions:
      - !Vector3 {x: 27, y: 17, z: 36}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      colors:
      - !RGB {r: 255, g: 0, b: 255}

    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 8, y: 20, z: 39}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 19, y: 23, z: 2}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      colors:
      - !RGB {r: 255, g: 0, b: 255}

    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 16, y: 12, z: 24}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
  3: !Arena
    passMark: 0
    timeLimit: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: HeavyBlock
      positions:
      - !Vector3 {x: 18, y: 34, z: 23}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}

    - !Item
      name: LightBlock
      positions:
      - !Vector3 {x: 34, y: 25, z: 10}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}

    - !Item
      name: JBlock
      positions:
      - !Vector3 {x: 22, y: 31, z: 22}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}

    - !Item
      name: LBlock
      positions:
      - !Vector3 {x: 29, y: 7, z: 32}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}

    - !Item
      name: UBlock
      positions:
      - !Vector3 {x: 22, y: 33, z: 34}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
  4: !Arena
    passMark: 0
    timeLimit: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: SpawnerButton # Interactive button that spawns rewards when triggered by the agent.
      positions:
      - !Vector3 {x: 32, y: 0, z: 30}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      moveDurations: [0.1] # the time it takes for the button to move forwards. This impacts the time the button can be pressed again.
      resetDurations: [1.0] # the time it takes for the button to move backwards. This impacts the time the button can be pressed again.
      rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"] # the list of rewards that can be spawned. The names must match the names of the rewards.
      rewardWeights: [100, 0, 0] # the weights of each reward in the rewards list respectively. The sum of all weights must be 100.
      spawnProbability: 1.0 # the probability of spawning the reward. 1.0 means 100% chance of spawning. 0.0 means 0% chance of spawning ANY reward.
      maxRewardCounts: [-1, -1, -1] # the maximum number of times each reward can be spawned. -1 means no limit respectively for each reward.
      rewardSpawnPos: !Vector3 {x: 25, y: 0, z: 23} # the position where the reward will be spawned upon pressing the button.
    - !Item
      name: SpawnerDispenserTall
      positions:
      - !Vector3 {x: 10, y: 0, z: 38}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      initialValues: [2.5]
      finalValues: [0.5]
      timesBetweenSpawns: [0.0]
      doorDelays: [0.0]
      spawnCounts: [10]

    - !Item
      name: SpawnerContainerShort
      positions:
      - !Vector3 {x: 16, y: 0, z: 30}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      initialValues: [2.5]
      finalValues: [0.5]
      timesBetweenSpawns: [0.5]
      doorDelays: [1.0]
      spawnCounts: [1]

    - !Item
      name: SpawnerTree
      positions:
      - !Vector3 {x: 3, y: 0, z: 10}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      initialValues: [2.5]
      finalValues: [0.5]
      ripenTimes: [4.0]
      timesBetweenSpawns: [0.5]
      spawnCounts: [10] 
  5: !Arena
    passMark: 0
    timeLimit: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: HotZone
      positions:
      - !Vector3 {x: 15, y: 1, z: 25}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}

    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 14, y: 0, z: 18}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}

    - !Item
      name: DataZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      zoneVisibility: true # Whether the zone is visible or not. If false, the zone will be invisible. True by default
      triggerZoneID: ["Agent entered Datazone located in the center of the arena."]